gitlab-server:
  ports:
    - ${ssh_port}:22/tcp
    - ${http_port}:${http_port}/tcp
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:latest
  volumes_from:
    - gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${gitlab_url_scheme}${gitlab_hostname}:${http_port}'
      ${gitlab_omnibus_config_extras}

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
    - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:latest
  volumes:
    - '${gitlab_volume_base}/config:/etc/gitlab'
    - '${gitlab_volume_base}/logs:/var/log/gitlab'
    - '${gitlab_volume_base}/data:/var/opt/gitlab'
